/*
 * JKeyedMulti.java
 *
 * Created on April 5, 2008, 8:16 PM
 */

package citibob.swing;

import citibob.swing.table.FixedColTableModel;
import citibob.types.JType;
import citibob.types.JavaJType;
import citibob.types.KeyedModel;
import java.util.ArrayList;
import java.util.Set;
import java.util.Vector;

/**
 
 @author  citibob
 */
public class JKeyedMulti extends javax.swing.JPanel
{

KeyedModel kmodel;
JType valueType;			// Type of value portion of kmodel
Vector vals;				// The values that we can return in our set
Set selected;					// The set of items selected

	/** Creates new form JKeyedMulti */
	public JKeyedMulti()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new citibob.swing.JTypeColTable();

        setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private citibob.swing.JTypeColTable table;
    // End of variables declaration//GEN-END:variables

// ===========================================================
static final String[] colNames = {"Chosen", "Item"};
static final boolean[] editable = {true, false};

static final int C_CHECK = 0;
static final int C_VALUE = 1;


//public class MyModel extends FixedColTableModel
//{
//
//	public MyModel(String[] colNames, JType[] types, boolean[] editable)
//	{
//		super(colNames,
//			new JType[] {JavaJType.jtBoolean, valueType},
//			editable);
//	}
//
//	public int getValueAt(int row, int col)
//	{
//		switch(col) {
//			case C_CHECK : return vals.get(row);
//		}
//	}
//public int getRowCount()
//	{ return data.size(); }
//
//public void clear() {
////	data.clear();
//	data = new ArrayList();
//	super.fireTableDataChanged();
//}
//}
	
}
