package citibob.gui;


import java.lang.reflect.Method;
import java.util.prefs.Preferences;
import javax.swing.DefaultListModel;

/*
 * AppLauncher.java
 *
 * Created on January 21, 2008, 8:05 PM
 */
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;



/**
 
 @author  fiscrob
 */
public class AppLauncher extends javax.swing.JFrame {

	/** Creates new form AppLauncher */
	public AppLauncher(Class[] classes) {
		initComponents();
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		DefaultListModel mod = new DefaultListModel();
		for (int i=0; i<classes.length; ++i) mod.addElement(classes[i]);
		lclasses.setModel(mod);
		
		lclasses.addListSelectionListener(new ListSelectionListener() {
		public void valueChanged(ListSelectionEvent event) {
			if (event.getValueIsAdjusting()) return;
			setVisible(false);
			Class klass = (Class)lclasses.getModel().getElementAt(event.getFirstIndex());
			try {
				System.out.println(klass);
				System.err.println(klass);
				Method[] meths = klass.getMethods();
				for (int i=0; i<meths.length; ++i)
				if ("main".equals(meths[i].getName())) {
					meths[i].invoke((Object)null, new String[]{null});
				}
			} catch(Exception e) {
				//e.printStackTrace(System.out);
				e.printStackTrace(System.err);
			}
			System.exit(-1);
		}});
		
		Preferences prefs = Preferences.userNodeForPackage(getClass()).node("AppLauncher");
		new citibob.swing.prefs.SwingPrefs().setPrefs(this, "", prefs);
	}
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lclasses = new javax.swing.JList();

        lclasses.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lclasses);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lclasses;
    // End of variables declaration//GEN-END:variables
	
	
public static void launch(Class[] classes) {
	AppLauncher launcher = new AppLauncher(classes); //new Class[]{String.class, Integer.class});
	launcher.setVisible(true);
}
}
